/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        background: '#151219',
        surface: '#151219',
        'surface-dim': '#151219',
        'surface-bright': '#3c373f',
        'surface-container-lowest': '#100d14',
        'surface-container-low': '#1e1a21',
        'surface-container': '#221e25',
        'surface-container-high': '#2c2830',
        'surface-container-highest': '#37333b',
        'on-surface': '#e8e0ea',
        'on-surface-variant': '#cdc3d4',
        'inverse-surface': '#e8e0ea',
        'inverse-on-surface': '#332f37',
        outline: '#978d9d',
        'outline-variant': '#4b4452',
        'surface-tint': '#dab9ff',
        primary: '#dab9ff',
        'on-primary': '#460283',
        'primary-container': '#bb86fc',
        'on-primary-container': '#4c0f89',
        'inverse-primary': '#7743b5',
        secondary: '#f7d22e',
        'on-secondary': '#3a3000',
        'secondary-container': '#d9b600',
        'on-secondary-container': '#574800',
        tertiary: '#17deca',
        'on-tertiary': '#003731',
        'tertiary-container': '#00b2a1',
        'on-tertiary-container': '#003d37',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#eedbff',
        'primary-fixed-dim': '#dab9ff',
        'on-primary-fixed': '#2a0053',
        'on-primary-fixed-variant': '#5e289b',
        'secondary-fixed': '#ffe16e',
        'secondary-fixed-dim': '#e8c41d',
        'on-secondary-fixed': '#221b00',
        'on-secondary-fixed-variant': '#544600',
        'tertiary-fixed': '#4ffbe6',
        'tertiary-fixed-dim': '#17deca',
        'on-tertiary-fixed': '#00201c',
        'on-tertiary-fixed-variant': '#005048',
        'on-background': '#e8e0ea',
        'surface-variant': '#37333b',
      },
      fontFamily: {
        display: ['Anton', 'sans-serif'],
        headline: ['Anton', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['"Space Grotesk"', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
